# Generated by Django 5.2.1 on 2025-05-21 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transportadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=18, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='ValePallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_vale', models.CharField(max_length=50, unique=True)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_validade', models.DateTimeField()),
                ('qtd_pbr', models.PositiveIntegerField(default=0)),
                ('qtd_chepp', models.PositiveIntegerField(default=0)),
                ('saldo_pbr', models.PositiveIntegerField(default=0)),
                ('saldo_chepp', models.PositiveIntegerField(default=0)),
                ('codigo_barras', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qrcodes/')),
                ('estado', models.CharField(choices=[('EMITIDO', 'Emitido'), ('UTILIZADO', 'Utilizado'), ('RETORNADO', 'Retornado'), ('CANCELADO', 'Cancelado')], default='EMITIDO', max_length=10)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('hash_seguranca', models.CharField(editable=False, max_length=32, unique=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controller.cliente')),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controller.motorista')),
                ('transportadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app_controller.transportadora')),
            ],
        ),
        migrations.CreateModel(
            name='Movimentacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SAIDA', 'Saída'), ('RETORNO', 'Retorno')], max_length=10)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('qtd_pbr', models.PositiveIntegerField(default=0)),
                ('qtd_chepp', models.PositiveIntegerField(default=0)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('vale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_controller.valepallet')),
            ],
            options={
                'db_table': 'movimentacoes',
                'ordering': ['-data_hora'],
            },
        ),
    ]
