# Generated by Django 5.2.1 on 2025-05-25 18:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nome'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='motorista',
            options={'ordering': ['nome'], 'verbose_name': 'Motorista', 'verbose_name_plural': 'Motoristas'},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data_hora'], 'verbose_name': 'Movimentação', 'verbose_name_plural': 'Movimentações'},
        ),
        migrations.AlterModelOptions(
            name='transportadora',
            options={'ordering': ['nome'], 'verbose_name': 'Transportadora', 'verbose_name_plural': 'Transportadoras'},
        ),
        migrations.AlterModelOptions(
            name='valepallet',
            options={'ordering': ['-data_emissao'], 'verbose_name': 'Vale Pallet', 'verbose_name_plural': 'Vales Pallets'},
        ),
        migrations.RemoveField(
            model_name='valepallet',
            name='codigo_barras',
        ),
        migrations.RemoveField(
            model_name='valepallet',
            name='saldo_chepp',
        ),
        migrations.RemoveField(
            model_name='valepallet',
            name='saldo_pbr',
        ),
        migrations.AddField(
            model_name='movimentacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valepallet',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cnpj',
            field=models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(help_text='Razão Social ou Nome Completo', max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='cpf',
            field=models.CharField(help_text='Formato: 000.000.000-00', max_length=14, unique=True, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='motorista',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='cnpj',
            field=models.CharField(help_text='Formato: 00.000.000/0000-00', max_length=18, unique=True, validators=[django.core.validators.MinLengthValidator(14)], verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='nome',
            field=models.CharField(max_length=255, verbose_name='Nome da Transportadora'),
        ),
        migrations.AlterField(
            model_name='transportadora',
            name='telefone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato: (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')], verbose_name='Telefone'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nome'], name='app_control_nome_0e455e_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['cnpj'], name='app_control_cnpj_ed8a4f_idx'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['nome'], name='app_control_nome_eb8313_idx'),
        ),
        migrations.AddIndex(
            model_name='motorista',
            index=models.Index(fields=['cpf'], name='app_control_cpf_da29e4_idx'),
        ),
        migrations.AddIndex(
            model_name='transportadora',
            index=models.Index(fields=['nome'], name='app_control_nome_14b15f_idx'),
        ),
        migrations.AddIndex(
            model_name='transportadora',
            index=models.Index(fields=['cnpj'], name='app_control_cnpj_41431c_idx'),
        ),
        migrations.AlterModelTable(
            name='movimentacao',
            table=None,
        ),
    ]
