# Generated by Django 5.2.1 on 2025-05-30 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0002_alter_cliente_options_alter_motorista_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('EMITIDO', 'Emitido'), ('SAIDA', 'Saida'), ('RETORNO', 'Retorno'), ('CANCELADO', 'Cancelado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='valepallet',
            name='estado',
            field=models.CharField(choices=[('EMITIDO', 'Emitido'), ('SAIDA', 'Saida'), ('RETORNO', 'Retorno'), ('CANCELADO', 'Cancelado')], default='EMITIDO', max_length=10),
        ),
    ]
    