# Generated by Django 5.2.1 on 2025-06-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0003_alter_movimentacao_tipo_alter_valepallet_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacao',
            name='data_validade',
            field=models.DateTimeField(null=True),
        ),
    ]
