# Generated by Django 5.2.1 on 2025-06-19 17:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0005_usuario_pessoajuridica_usuario_unique_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_controller.pessoajuridica', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='motorista',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_controller.pessoajuridica', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='transportadora',
            name='criado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='app_controller.pessoajuridica', verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='valepallet',
            name='data_retorno',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valepallet',
            name='data_saida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valepallet',
            name='usuario_retorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_retorno', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Retorno'),
        ),
        migrations.AddField(
            model_name='valepallet',
            name='usuario_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_saida', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da saída'),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='data_validade',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='movimentacao',
            name='tipo',
            field=models.CharField(choices=[('EMITIDO', 'Emitido'), ('SAIDA', 'Saida'), ('RETORNO', 'Retorno'), ('CANCELADO', 'Cancelado'), ('SCAN', 'Scan QR Code')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pessoajuridica',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoa_juridica', to=settings.AUTH_USER_MODEL, verbose_name='Usuário responsável'),
        ),
        migrations.AlterField(
            model_name='valepallet',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_criados', to='app_controller.pessoajuridica', verbose_name='Criado por'),
        ),
    ]
