# Generated by Django 5.2.1 on 2025-06-18 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0006_cliente_criado_por_motorista_criado_por_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valepallet',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vales_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AlterField(
            model_name='valepallet',
            name='usuario_retorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_retornp', to='app_controller.pessoajuridica', verbose_name='Usuario Retorno'),
        ),
        migrations.AlterField(
            model_name='valepallet',
            name='usuario_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_saida', to='app_controller.pessoajuridica', verbose_name='Usuário da saída'),
        ),
    ]
