# Generated by Django 5.2.1 on 2025-06-18 22:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0008_alter_valepallet_usuario_retorno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valepallet',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vales_criados', to='app_controller.pessoajuridica', verbose_name='Criado por'),
        ),
    ]
