# Generated by Django 5.2.1 on 2025-06-19 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0009_alter_valepallet_criado_por'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valepallet',
            name='criado_por',
            field=models.ForeignKey(blank=True, db_column='criado_por', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_criados', to='app_controller.pessoajuridica', verbose_name='Criado por'),
        ),
    ]
