# Generated by Django 5.2.3 on 2025-06-25 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0007_alter_usuario_groups_alter_usuario_telefone_and_more'),
        ('app_controller', '0010_alter_valepallet_criado_por'),
    ]

    operations = [
    ]
