# Generated by Django 5.2.3 on 2025-06-25 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controller', '0011_merge_20250625_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valepallet',
            name='usuario_retorno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_retorno', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Retorno'),
        ),
        migrations.AlterField(
            model_name='valepallet',
            name='usuario_saida',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vales_saida', to=settings.AUTH_USER_MODEL, verbose_name='Usuário da saída'),
        ),
    ]
